- src/InlineHelp/InlineHelp.Component.js
- src/InlineHelp/InlineHelp.js
- src/Routes.js
- src/index.js
This pull request is for creating an Inline Help component
https://github.com/SAP/fundamental-react/issues/6
> Inline help Component (Feature Request - Issue #6)

- src/Pagination/Pagination.Component.js
- src/Pagination/Pagination.js
- src/Routes.js
- src/index.js
Initial commit of the Pagination control. This control will allow users to display a collection of links (page numbers) as well as a Previous and Next button. The total number of pages is determined by the total number of items.
This control is for the issue: https://github.com/SAP/fundamental-react/issues/11
> Pagination control

- src/MegaMenu/MegaMenu.js
Hi there 👋 !
I know this control might be retired soon 😄 but  I fixed some console warnings (probably from webpack ).
Also I fixed a tiny issue when clicking on an item list with children it was staying selected.
For example:
Thanks
Ramona 🐳
> fix for megamenu console warnings & selection issue

- src/App.scss
- src/Breadcrumb/Breadcrumb.Component.js
- src/Breadcrumb/Breadcrumb.js
- src/Icon/Icon.Component.js
- src/MegaMenu/MegaMenu.Component.js
- src/MegaMenu/MegaMenu.js
- src/SideNavigation/SideNavigation.Component.js
- src/SideNavigation/SideNavigation.js
> Issue#13: adds link and url options for Breadcrumb, SideNav and MegaMenu

- src/Routes.js
- src/SearchInput/SearchInput.Component.js
- src/SearchInput/SearchInput.js
- src/index.js
Created Search Input component for #39 
Add 2 styles:
Default: Plain input box with Search button
Auto-complete: If a user passes a onAutoComplete method to handle the search input entered
Did not include the <strong/> tags around text in list items in this version
> Search input

- src/Alert/Alert.Component.js
- src/Calendar/Calendar.js
- src/DatePicker/DatePicker.js
- src/Forms/Forms.js
- src/InputGroup/InputGroup.js
- src/MegaMenu/MegaMenu.js
- src/Routes.js
- src/Table/Table.js
- src/Tabs/Tabs.Component.js
- src/Tabs/Tabs.js
- src/Tag/Tag.js
- src/Tile/Tile.Component.js
- src/Tree/Tree.js
- src/documentation/Playground/Playground.js
Reduced the number of eslint warnings. Majority of warnings were == found instead of === as well as variables being defined but are never used. Also updated check for NaN to use the IsNaN() method instead of using: number != NaN
> reduce eslint warnings

- src/SearchInput/SearchInput.js
Without this check for data property, if just the onAutoComplete value is set the page breaks.
> fix breaking error, check for data prop to be set for Auto Complete

- src/MultiInput/MultiInput.Component.js
- src/MultiInput/MultiInput.js
- src/Routes.js
- src/index.js
Created Multi Input component for Issue: #38 
Issue #45 needs to be completed for the Tag styling to be correct.
> Multi input component

- CONTRIBUTING.md
- UNIT-TESTING.md
For Issue #30 
Jest and Enzyme are configured for unit testing. Here is some documentation on how to get setup
> Unit testing doc

- package-lock.json
- package.json
- src/ActionBar/ActionBar.js
- src/ActionBar/__snapshots__/ActionBar.test.js.snap
- src/Alert/Alert.js
- src/Badge/Badge.js
- src/InlineHelp/InlineHelp.Component.js
- src/InlineHelp/InlineHelp.js
- src/InlineHelp/InlineHelp.test.js
- src/InlineHelp/__snapshots__/InlineHelp.test.js.snap
- src/documentation/Playground/Playground.js
migrates to v1.3.2, adds bottom-center position for the inline help and updates the tests for inline-help
> Issue#67: migration to v1.3.2

- src/ActionBar/__snapshots__/ActionBar.test.js.snap
- src/MegaMenu/MegaMenu.test.js
- src/MegaMenu/__snapshots__/MegaMenu.test.js.snap
- src/SideNavigation/SideNavigation.test.js
- src/SideNavigation/__snapshots__/SideNavigation.test.js.snap
- src/Time/Time.test.js
- src/Time/__snapshots__/Time.test.js.snap
item #30 add coverage and unit test for MegaMenu, and update for Time component
> Unit test updates

- src/Identifier/Identifier.js
- src/Identifier/Identifier.test.js
- src/Identifier/__snapshots__/Identifier.test.js.snap
- src/Image/Image.js
- src/Image/Image.test.js
- src/Image/__snapshots__/Image.test.js.snap
- src/ListGroup/ListGroup.test.js
- src/ListGroup/__snapshots__/ListGroup.test.js.snap
- src/Navbar/__snapshots__/Navbar.test.js.snap
- src/Popover/Popover.js
- src/Popover/Popover.test.js
- src/Tabs/Tabs.js
- src/Tile/Tile.test.js
- src/Tile/__snapshots__/Tile.test.js.snap
issue #30 
- Identifier & image components, removed if check for size, since size is a required field
- Removed duplicate prop in Popover component for **ref**
- Updated Tabs component to fix eslint warning
> updated unit test coverage and eslint warnings

- src/InputGroup/InputGroup.js
- src/InputGroup/InputGroup.test.js
- src/InputGroup/__snapshots__/InputGroup.test.js.snap
input group type text was having an issue making the text box uneditable.
> Input group fix

- src/Modal/Modal.Component.js
> clean up of class -> className

- UNIT-TESTING.md
- package-lock.json
- package.json
- src/TimePicker/TimePicker.js
- src/TimePicker/TimePicker.test.js
- src/TimePicker/__snapshots__/TimePicker.test.js.snap
- src/Tree/Tree.js
- src/Tree/Tree.test.js
updated unit test documentation
> added unit test and coverage for TimePicker

- src/Calendar/Calendar.test.js
- src/Identifier/Identifier.test.js
- src/Identifier/__snapshots__/Identifier.test.js.snap
Just got latest and ran unit tests, Calendar fails because didn't test Date change properly, hopefully this solves future issues :)
> fix calendar unit test failing

- package-lock.json
- package.json
- src/Calendar/Calendar.test.js
Because of security vulnerabilities in npm, an update to webpack-dev-server are needed
https://www.npmjs.com/advisories/725
> Update webpack dev server

- package.json
> fix: remove beta

- .travis.yml
- package-lock.json
- package.json
Edits travis file to run deploy on master, includes standard-version in package.json
> fix: add standard-version to package.json

- .travis.yml
This line was necessary as PR requests to master were trigger a deploy
> fix: add pack PR limiter

- .travis.yml
- ci-scripts/publish.sh
This pr removes automation added for versioning and releasing for the develop/master model. A followup PR will be added tomorrow to reenable this feature to follow the rc model.
> fix: removing automation centered on development branch

- package-lock.json
- package.json
Fundamental-bot did not have the correct permissions to push directly to the master branch, therefore the version on npm is not synchronized with package.json.
This pr will also test that fundamental-bot has appropriate permissions. 🤞
> fix: bump rc version manually due to failure in travis

- README.md
- package-lock.json
- package.json
testing new branch protections
> fix: manually updating rc version

- ci-scripts/publish.sh
- package-lock.json
- package.json
Adding verbose flag and git status to help determine where the push is going wrong.
> fix: add verbose to push output in travis

- ci-scripts/publish.sh
- package-lock.json
- package.json
Remove git status, test with removed branch protections
> fix: remove git status 

- package-lock.json
- package.json
attempt with _all_ branch protections applied
> fix: manually bump package version

- README.md
testing with branch protections enabled
> fix: testing with branch protections

- README.md
removing newline on readme
testing branch protections - CLA signed required
> fix: remove newline on readme

- README.md
testing with branch protection - travis ci required enabled
> fix: testing with travis branch protections required

- CHANGELOG.md
Restrict who can push to matching branches
> fix: testing travis with branch protection - Restrict who can push to matching branches

- .eslintrc
- src/Time/Time.js
Enabled the `radix` eslint rule and fixed lint errors.
> fix: eslint radix

- .travis.yml
- README.md
repoint travis to our new public slack workspace: ui-fundamentals
> fix: update slack location for travis notifications

- .travis.yml
- package-lock.json
update node version to the current LTS version (currently 10.15.0)
fixes #170
> fix: update travis node version.

- src/Calendar/Calendar.Component.js
- src/Calendar/Calendar.js
- src/Calendar/Calendar.test.js
spreading props to Calendar component
> fix: prop spreading to Calendar

- .editorconfig
Fixes https://github.com/SAP/fundamental-react/issues/174.
Link to more info: http://EditorConfig.org
Link to vscode plugin: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
> fix: add editor config file

- src/MultiInput/MultiInput.Component.js
- src/MultiInput/MultiInput.js
- src/MultiInput/MultiInput.test.js
Prop spreading for sub elements
tests
documentation
> fix: prop spreading for MultiInput

- src/Shellbar/Shellbar.Component.js
Update the Shellbar code sample "Links with collapsible menu, CoPilot and Product Switcher" so that it is the same as the executable version below.
See: https://github.com/SAP/fundamental-react/blob/f52723f89be928e90e6828aa2c818e1d98ad1537/src/Shellbar/Shellbar.Component.js#L506
> fix: Fix typo in Shellbar code sample

- src/Tabs/Tabs.Component.js
- src/Tabs/Tabs.js
- src/Tabs/Tabs.test.js
Added prop spreading to Tabs and TabComponent
> fix: prop spreading to Tabs

- src/MegaMenu/MegaMenu.Component.js
- src/MegaMenu/MegaMenu.js
- src/MegaMenu/MegaMenu.test.js
Prop spreading to MegaMenu components
Tests
Documentation
> fix: MegaMenu prop spreading

- src/TimePicker/TimePicker.Component.js
- src/TimePicker/TimePicker.js
- src/TimePicker/TimePicker.test.js
- Spread props for TimePicker
- Update unit tests
- Update docs
> fix: Spread props for TimePicker

- package-lock.json
- src/Forms/Forms.js
- src/Forms/__snapshots__/Forms.test.js.snap
> fix: add * to required form labels

- .travis.yml
enable caching of node_modules in travis (per branch)
fixes https://github.com/SAP/fundamental-react/issues/262
> chore: enable caching of node_modules

- src/Tree/Tree.test.js
add new unit test to make Tree component 100% covered
> fix: Update Tree component unit test to 100%

- src/SearchInput/SearchInput.js
> fix: fixes #279 Add `event` argument to onChange props in SearchInput

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
this will pre-populate the textarea seen when creating a new issue.
> fix: add issue template

- .eslintrc
one missing a11y rule. adding.
> fix: add missing a11y lang rule

- src/SearchInput/SearchInput.js
- src/SearchInput/SearchInput.test.js
- src/SearchInput/__snapshots__/SearchInput.test.js.snap
Update SearchInput code coverage to 100%
> Fix: search input unit tests

- src/Popover/Popover.test.js
Update unit test for Popover component to 100% code coverage
> fix: update Popover code coverage to 100%

- src/_playground/App.scss
- src/_playground/documentation/DocsTile/DocsTile.js
- src/_playground/documentation/Separator/Separator.js
Cleaning up inline styles for playground components so that they can be reused later and reduced repeat css. 
fixes #issueid
> chore: cleanup inline styles in playground

- src/Calendar/Calendar.js
- src/Calendar/Calendar.test.js
Refactored Calendar component, removed unused methods. Update unit tests and improved code coverage
> fix: update unit test, refactor code for Calendar

- src/Modal/Modal.Component.js
Fix ModalComponent file, change onclick to onClick
fixes #350
> fix: Modal documentation console error

- src/DatePicker/DatePicker.js
- src/DatePicker/DatePicker.test.js
Added check for entered in date string and date range string to see if dates entered are disabled. If dates are disabled, removed text string and date selection
fixes #338
> fix: DatePicker prevent ability to enter in disabled date string

- README.md
Adds bundlephobia badges to readme
> chore: add bundlephobia badges

- src/Calendar/Calendar.js
Adding missing style to other months dates
fixes #365
> fix: adding missing style to other months dates

- package-lock.json
- package.json
- src/Modal/Modal.js
Added [FocusTrap](https://github.com/davidtheclark/focus-trap-react) react library to Modal component to handle Focus trapping when cycling through Modal box. 
Added attributes to Modal dialog box:
- aria-label={title}
- aria-modal='true'
- role='dialog'
fixes #345
> fix: Added FocusTrap to Modal component

- src/Badge/Badge.Component.js
- src/Button/Button.Component.js
- src/ContextualMenu/ContextualMenu.Component.js
- src/Forms/Forms.Component.js
- src/Image/Image.Component.js
- src/ListGroup/ListGroup.Component.js
- src/Toggle/Toggle.Component.js
- src/Token/Token.Component.js
- src/_playground/App.scss
- src/_playground/documentation/Description/Description.js
- src/_playground/documentation/Playground/Playground.js
- src/utils/constants.js
Many of the playground pages had console warnings due to the Description component and several other small issues. 
The only remaining warnings will be solved by #359 
fixes #325 
fixes #360
> chore: fix warnings on playground pages

- package.json
add `description` to `package.json`
fixes #383
> chore: #383 add description to package.json

- .eslintrc
- src/ActionBar/ActionBar.js
- src/ActionBar/ActionBar.test.js
- src/Alert/Alert.js
- src/Alert/Alert.test.js
- src/Badge/Badge.js
- src/Button/Button.js
- src/Forms/Forms.Component.js
- src/Forms/Forms.test.js
- src/Icon/Icon.js
- src/Identifier/Identifier.js
- src/Image/Image.js
- src/InlineHelp/InlineHelp.js
- src/InputGroup/InputGroup.js
- src/ListGroup/ListGroup.Component.js
- src/ListGroup/ListGroup.test.js
- src/MultiInput/MultiInput.test.js
- src/Panel/Panel.Component.js
- src/Panel/Panel.test.js
- src/Popover/Popover.Component.js
- src/Popover/Popover.js
- src/SideNavigation/SideNavigation.js
- src/SideNavigation/SideNavigation.test.js
- src/Time/Time.test.js
- src/TimePicker/TimePicker.test.js
- src/Toggle/Toggle.js
- src/Toggle/Toggle.test.js
- src/_playground/documentation/DocsTile/DocsTile.js
- src/_playground/documentation/Header/Header.js
- src/_playground/documentation/Import/Import.js
Add and applies the [object-curly-spacing](https://eslint.org/docs/rules/object-curly-spacing) eslint rule
> chore: Add eslint rule object-curly-spacing

- config/paths.js
- package-lock.json
- package.json
This command allows devs to serve a 'production' build of the docs site locally for debugging purposes.
> chore: add command to serve docs locally

- src/_playground/documentation/Properties/Properties.js
> chore: (playground) Recurse on propTypes for Properties table

- src/_playground/App.scss
- src/_playground/Routes.js
Fixes #459 Added hidden skip navigation link in header that allows the user to skip to the main content.
> docs: skip nav link to header

- src/_playground/documentation/utils/CustomPropTypes.js
Added CustomPropTypes file in order to begin shaping localizedText PropTypes
This is prework needed for adding a localizedText prop, tracked here: https://github.com/SAP/fundamental-react/wiki/localizedText-shape-Prop-for-All-Components
fixes #issueid
> fix:added CustomPropTypes file

- src/_playground/App.scss
- src/_playground/documentation/Properties/_PropertyTable.js
- src/_playground/documentation/Properties/_PropertyType.js
Edits from [#477](https://github.com/SAP/fundamental-react/pull/477)
This is prework needed for adding a localizedText prop, tracked here: https://github.com/SAP/fundamental-react/wiki/localizedText-shape-Prop-for-All-Components
> fix: continued PropertyTable edits

- src/Badge/Counter.js
- src/_playground/documentation/Properties/_PropertyShape.js
- src/_playground/documentation/Properties/_PropertyTable.js
Added Description column to localized text table
This is continued work needed for adding a localizedText prop, tracked here: https://github.com/SAP/fundamental-react/wiki/localizedText-shape-Prop-for-All-Components
> fix: Added description to localized text property table

- src/Alert/Alert.js
> fix: Added localized text shape to alert

- src/Pagination/Pagination.js
> fix: localizedText shape for pagination

- src/InputGroup/InputGroup.js
Current Component: Input Group
> fix: added localized text shape to input group

- src/Modal/Modal.js
> fix: added localized text shape to Modal

- src/MultiInput/MultiInput.js
Current Component: Multi Input
> fix: added localized text shape for multi input component

- src/Shellbar/Shellbar.js
> fix: added localized text shape for shellbar

- src/Calendar/Calendar.js
- src/_playground/documentation/Properties/_PropertyDefault.js
- src/_playground/documentation/Properties/_PropertyTable.js
Current Component: Calendar
* Needed to update propertydefault.js to include arrays
* Needed to update propertyTable.js to fix bug in propDescriptions
> fix: added localized text shape to calendar

- src/Alert/Alert.js
- src/InputGroup/InputGroup.js
- src/Modal/Modal.js
- src/MultiInput/MultiInput.js
- src/Pagination/Pagination.js
- src/Shellbar/Shellbar.js
> fix: propdescription change to localizedTextShape

- src/Time/Time.js
- src/Time/_TimeItem.js
> fix: added localizedText prop to time

- src/TimePicker/TimePicker.js
- src/TimePicker/_TimePickerItem.js
Current Component: Time Picker
> fix: add time picker localized text shape

- src/Popover/Popover.js
- src/Popover/Popover.test.js
Added callbacks onClickOutside and onEscapeKey to popover with tests
separate PR linked to https://jira.concur.com/browse/CORUI-6332.
fixes #issueid
> Fix: added callbacks onClickOutside and onEscapeKey to popover with tests

- src/MultiInput/MultiInput.js
- src/MultiInput/MultiInput.test.js
Implemented Popover in multi input component
Portion of story - https://jira.concur.com/browse/CORUI-6332 
fixes #issueid
> fix: Implemented popover for multiInput

- package-lock.json
- package.json
> chore: hat babel core

- babel.config.js
- ci-scripts/publish-rc.sh
- ci-scripts/publish.sh
- package-lock.json
- package.json
See https://github.com/SAP/fundamental-react/pull/772, separates umd from babel changes.
Output of dry run: 
fixes #774
> fix: update publish

- package-lock.json
- src/Dropdown/Dropdown.Component.js
- src/Popover/Popover.Component.js
- src/Popover/Popover.js
- src/Popover/Popover.test.js
- src/utils/_Popper.js
- src/utils/constants.js
Clone of https://github.com/SAP/fundamental-react/pull/789 in order to resolve conflicts.
fixes #issueid
> fix: align popover inside dropdown

- CHANGELOG.md
- package-lock.json
- package.json
woops
already deleted tags, waiting on user login from @droshev to be able to delete the published versions on npm.
> chore: manually create 0.8.0-rc.8

- src/TimePicker/TimePicker.js
- src/TimePicker/TimePicker.test.js
- src/TimePicker/_TimePickerItem.js
- src/TimePicker/__snapshots__/TimePicker.test.js.snap
The TimePicker component does not have a way in which we can get the selected time. It should have an onChange method implemented that can be leveraged to get the selected time.
fixes #857
> fix: Implemented onChange method for TimePicker component to get selected time

- NOTICE.txt
- README.md
> chore: update copyright year references

- src/TimePicker/TimePicker.Component.js
- src/TimePicker/TimePicker.js
- src/TimePicker/TimePicker.test.js
- src/TimePicker/__snapshots__/TimePicker.test.js.snap
There is no provision to set an inital time value(default value) to the Time Picker Component.
According to the documentation, value prop can be used to set initial values but its not working.
Fixed this issue in this.
fixes #issueid
Issue#915
> fix:#915 Unable to set initial time value for the time picker input

- src/DatePicker/DatePicker.js
- src/DatePicker/DatePicker.test.js
> fix: add new onDatePickerClose callback to DatePicker component

- .github/CONTRIBUTING.md
We've made some changes + needed to update some links.
fixes #issueid
> chore: update contribution guidelines

- src/Popover/Popover.js
- src/SearchInput/SearchInput.js
- src/SearchInput/SearchInput.test.js
> fix: Close SearchInput popover after selecting an item.

- src/Pagination/Pagination.js
- src/Pagination/Pagination.test.js
- src/Pagination/__stories__/Pagination.stories.js
- src/Pagination/__stories__/__snapshots__/Pagination.stories.storyshot
> fix: #1011 Pagination - Fixed missing interraction as defined in fundamental-styles

- .storybook/main.js
- .storybook/preview.js
> chore: storybook default landing page to introduction

- src/SearchInput/SearchInput.js
- src/SearchInput/SearchInput.test.js
read search list from props directly
fixes #1012
> fix: SearchInput doesn't updated when searchList property change

- package-lock.json
- package.json
Use cross-env for windows compatibility. 
fixes #issueid
> chore: add cross-env to env variables in package.json

- src/Button/__stories__/Button.stories.js
- src/Button/__stories__/__snapshots__/Button.visual.storyshot
- src/utils/constants.js
Fix for #1033 
Added new types 'ghost' and 'attention' to Button Component
fixes #issueid
> feat: #1033 Button-update-styles-to-include-new-types-`ghost`-and-`attention` 

- .storybook/manager-head.html
possible way to make the sidebar header stick to the top
> fix: style sidebar

- .storybook/main.js
- CHANGELOG.md
- package-lock.json
- package.json
- src/StepInput/StepInput.js
- src/StepInput/StepInput.test.js
- src/StepInput/__stories__/StepInput.stories.js
Added onchange callback in stepInput props
fixes #1073
> fix: #1073Added onchange callback in stepInput props

- .github/CONTRIBUTING.md
- .github/workflows/greetings.yml
- .github/workflows/stale.yml
> chore: add greeting and stale pull request actions

- src/Select/Select.js
Add support for an optional prop that allows custom styling on the option dropdown list.
> fix: add prop for Select dropdown styling

- src/List/_ListItem.js
- src/Select/Select.js
- src/Select/Select.test.js
New classes:
`controlClassName`
`triggerClassName`
`textContentClassName`
`listItemClassName`
`listItemTextClassName`
fixes #issueid
> feat: add custom classes to Select component

- package-lock.json
- package.json
- src/Shellbar/Shellbar.js
- src/Shellbar/__stories__/Shellbar.stories.js
- src/Shellbar/__stories__/__snapshots__/Shellbar.stories.storyshot
BREAKING CHANGE: 
- notifications component refactored. Removed classes: fd-notification--information, fd-notification--success, fd-notification--warning, fd-notification--error
- rename the delta theming parameters with fd prefix ([#1660](https://github.com/SAP/fundamental-styles/issues/1660))
- rename our CSS variables prefix from --sap to --fd (--sapInverted_Object_Border_Width, --sapOverlay_Background_Opacity, --sapRating_Indicator_Selected_Hover_Opacity, --sapRating_Indicator_Display_Only_Selected_Color, --sapRating_Indicator_Disabled_Selected_Color, --sapRating_Indicator_Disabled_Unselected_Color, --sapRating_Indicator_Disabled_Control_Opacity)
- Add support for `Shellbar` component size modifiers. 
- Create knobs and example for providing sizes for `Shellbar`.
> feat: update fundamental-styles to 0.12.0-rc.64

- .storybook/main.js
- README.md
- src/Dialog/Dialog.js
- src/InputGroup/InputGroup.js
- src/LocalizationEditor/LocalizationEditor.js
- src/MultiInput/MultiInput.js
- src/Shellbar/Shellbar.js
- src/SideNavigation/_SideNavListItem.js
- src/StepInput/StepInput.js
fix isCssModulesEnabled check when styles is undefined and improve setup in README
fixes #issueid
> fix: fix isCssModulesEnabled check when styles is undefined and improve setup in README

- src/DatePicker/DatePicker.test.js
Fix the failing build on the master branch after I merged the last PR
fixes #issueid
> fix: Fix breaking datepicker test with merge

- .github/CONTRIBUTING.md
- .github/workflows/greetings.yml
- .travis.yml
- README.md
- ci-scripts/publish.sh
- scripts/publish-release.sh
There is migration from master to branch - it will require additional steps, to fully work. They are listed there:
SAP/fundamental-ngx#3554
> chore: Migrate master to main

- .travis.yml
update node version to 15.11.0 for travis
> chore: update node version to 15.11.0 for travis

- ci-scripts/publish-rc.sh
- ci-scripts/publish.sh
- package-lock.json
- package.json
> chore: update bump version

- .github/in-solidarity.yml
> chore(deps-dev): add in-solidarity.yml file

- src/Dialog/Dialog.js
> fix: allow lock focus for specific list 

- src/ComboboxInput/ComboboxInput.js
> feat: Combobox: explicitly check if typedValue is a string

- src/Dialog/Dialog.js
- src/Dialog/Dialog.test.js
Restore original scroll position
fixes #1395
> feat: preserve scroll position

- src/Shellbar/Shellbar.js
> feat: add onclick on actions, revert compact for product switch

- README.md
> fix: add set environment tips

- CHANGELOG.md
> docs: Add CHANGELOG for broken changes
