src/Modal/Modal.Component.js
src/Modal/Modal.js
src/MultiInput/MultiInput.Component.js
src/MultiInput/MultiInput.js
src/Routes.js
src/index.js

Update modal component to handle show/hide by **show** property in the component.

Modal component update

---

src/DatePicker/DatePicker.test.js
src/Time/Time.js
src/Time/Time.test.js
src/TimePicker/TimePicker.js
src/Tree/Tree.test.js
src/Tree/__snapshots__/Tree.test.js.snap

#30 update unit tests for tree, time and datepicker

Update unit tests

---

.travis.yml
package.json

code coverage was available, but not reported in Travis. This corrects that
fixes: #114
see:

fix: init coverage

---

.eslintignore
.eslintrc
package.json

once a .eslintrc was made available, it invalidated
```
"eslintConfig": {	
"extends": "react-app"	
}
```
in the package.json.  
Moved the extension to eslintrc, where i found out that rules under this extension are failing (and have always been - lint was never a limiting factor to the repo before), so it is commented out for now, like other failing rules that need to be addressed.

fix: move lint extend react-app to eslintrc. comment out due to failing rules

---

src/documentation/DocsTile/DocsTile.js

Hi 👋 ,
implementation of copy button for code snippets for playground.
_PS: can someone test it for Internet explorer 😄_ ?
thanks
Ramona 🐳

Implement a "copy" button in the playground code snippets

---

README.md
package-lock.json
package.json

#137 downgrade the version of webpack-dev-server to 3.19 as react-script@2.1.2 depends on that version

#137 downgrade the version of webpack-dev-server to 3.19

---

.travis.yml
ci-scripts/publish.sh
ci-scripts/setup_npm.sh
package.json

Hello 👋 
I've been working on automating versioning and publishing via the travis build.
@droshev Could you add the following environmental variables to travis here: https://travis-ci.org/SAP/fundamental-react/settings
* `GH_TOKEN` (Github access token for publishing back to the repo - we use a build account)
* `NPM_EMAIL`  
* `NPM_USERNAME`
* `AUTH_TOKEN`  (access token from npm account)
* `NPM_PASSWORD`
How this works: 
Every time we merge `develop` into `master`, the [standard-version](https://github.com/conventional-changelog/standard-version) package will automatically bump the version in `package.json` and `package-lock.json` as well as update the `CHANGELOG.md` with commit information. The commit message will be `chore(release): version x.x.x build x [ci skip] `. 
Standard-version …

feat: automate versioning and publish via travisci

---

.travis.yml
ci-scripts/publish.sh

Move deploy to it's own stage so that it doesn't run in all jobs.

fix: move deploy to jobs

---

ci-scripts/publish.sh

Adding git status and echoing travis_branch to determine where push is failing

fix: add git status to publish script

---

package-lock.json
package.json

Manually bump package version to aid in debugging - prevent standard-version failure (tag already exists in npm).

fix:  manually bump version to stop stdversion failure

---

ci-scripts/publish.sh
ci-scripts/publish_release.sh

Adds fundamental-bot to release script as it has admin rights to push to master.
Fixes regex where there was possible failures due to use of `/s` for whitespace.

fix: add fundamental bot to release script

---

.eslintrc
src/Tree/Tree.test.js

Enabled the `no-sparse-arrays` eslint rule and fixed lint errors.

fix: eslint no sparse arrays

---

.eslintrc

Enabled the `react-in-jsx-scope` eslint rule.

fix: eslint react in jsx scope

---

.eslintrc
src/Calendar/Calendar.js

Enabled the `no-nested-ternary` eslint rule and fixed lint errors.

fix: eslint no nested ternary

---

.eslintrc
src/Time/Time.js

Enabled the `no-empty` eslint rule and fixed lint errors.

fix: eslint no empty

---

.eslintrc
src/MultiInput/MultiInput.test.js
src/Table/Table.js

Enabled the `no-shadow` eslint rule and fixed lint errors.

fix: eslint no shadow

---

.eslintrc
src/Alert/Alert.js
src/Calendar/Calendar.js
src/Modal/Modal.Component.js
src/documentation/Playground/Playground.js

Enabled the `no-undefined` eslint rule and fixed lint errors.

fix: eslint no undefined

---

.eslintrc
package-lock.json
package.json
src/registerServiceWorker.js

Enabling compat/compat rule
The only place this needed changes was in registerServiceWorker - service workers are not compatible with internet explorer: https://caniuse.com/#feat=serviceworkers
Therefore, we do not need to refactor the registerServiceWorker file to be compatible with IE because that capability would not work for IE users anyways.

fix: enable compat/compat eslint rule

---

.eslintrc
src/DatePicker/DatePicker.js

Enabled the `valid-typeof` eslint rule and fixed lint errors.

fix: eslint valid typeof

---

src/Menu/Menu.Component.js
src/Menu/Menu.js
src/Menu/Menu.test.js

Add props spreading to the Menu component

fix: props spreading to Menu

---

src/Breadcrumb/Breadcrumb.js
src/Breadcrumb/Breadcrumb.test.js
src/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap

allow prop spreading to Breadcrumb

fix: prop spreading to breadcrumb

---

src/Pagination/Pagination.Component.js
src/Pagination/Pagination.js
src/Pagination/Pagination.test.js
src/Pagination/__snapshots__/Pagination.test.js.snap

include displayTotalProps and linkProps in the documentation for Pagination component

fix: update doc, add pagination spread props

---

src/ActionBar/ActionBar.Component.js
src/ActionBar/ActionBar.js
src/ActionBar/ActionBar.test.js

Adds additional props to enable spreading into button, h1 and p elements.

fix: update prop spreading for ActionBar

---

src/Alert/Alert.Component.js
src/Alert/Alert.js
src/Alert/Alert.test.js
src/Alert/__snapshots__/Alert.test.js.snap
src/_playground/documentation/Playground/Playground.js

Fixes https://github.com/SAP/fundamental-react/issues/234

fix: rename dismissable to dismissible in Alert component

---

src/Toggle/Toggle.Component.js
src/Toggle/Toggle.js
src/Toggle/Toggle.test.js

- Spread props to Toggle's elements
- Update unit tests
- Update docs

fix: Prop spreading to Toggle

---

src/Button/Button.js
src/Button/Button.test.js

Allows props to be spread to ButtonGroup component

fix: prop spreading to ButtonGroup

---

src/SideNavigation/SideNavigation.js
src/SideNavigation/SideNavigation.test.js

- Spread props to SideNavigation's elements
- Update unit tests
The documentation for this component didn't include the props for the component that I added prop spreading to so I didn't update docs.

fix: Prop spreading for SideNavigation

---

src/Time/Time.Component.js
src/Time/Time.js
src/Time/Time.test.js

- Spread props to Time's elements
- Update unit tests
- Update docs

fix: Prop spreading for Time

---

src/Table/Table.Component.js
src/Table/Table.js
src/Table/Table.test.js

**NOTE:** This supports prop spreading to the table, table header, table header row, table body and table body rows.  The API currently prevents easily prop spreading to table cells so I created a follow-up issue (#259) for that work.

fix: Prop spreading for Table

---

README.md

This section for consuming the library was accidentally removed in a previous pr. Updates include reference only to App.scss as mentioned in https://github.com/SAP/fundamental-react/issues/267 and included import sample.

chore: update readme for consuming library

---

.travis.yml
ci-scripts/publish.sh
ci-scripts/publish_release.sh
package.json

Change logic for publishing releases.
`npm run release` will checkout a new branch on your local machine called `automated_travis_release_do_not_use` and use `git push` to trigger a travis build. Travis will then run a deployment based off branch names. Merges to master will still result in a rc release, while builds from `automated_travis_release_do_not_use` will result in a release.
`automated_travis_release_do_not_use` will then be deleted both locally and remotely to ensure this works for multiple releases.

fix: update publishing script for releases

---

ci-scripts/publish.sh

Adds gh-pages release to publish script. Tested that this does run predeploy and deploy at the same time.

chore: add gh deploy script to publish

---

.eslintrc
src/_playground/documentation/Playground/Playground.js

Add onBlur to playground component's <select> elements. Another option is to remove the onChange events from these <select> elements entirely. 
#245

fix: Playground component to use onBlur and onChange

---

src/Alert/Alert.Component.js
src/ListGroup/ListGroup.Component.js
src/ListGroup/ListGroup.test.js
src/Table/Table.Component.js

Disabling lint rule on component documentation pages. This is prework for changes needed in ShellBar and Pagination before the lint rule can be fully enabled.
#245

chore: disable anchor a11y rule on documentation pages

---

src/Pagination/Pagination.js
src/Pagination/__snapshots__/Pagination.test.js.snap

Following error occurs when loading Pagination control - 
React does not recognize the `initialPage` prop on a DOM element.
fixes #303

fix: initialPage error on component load

---

config/webpack.config.prod.js
package.json
scripts/build.js

In order to get proptypes working, we need to be development mode when we deploy to github pages. This is a stop gap measure for the meantime and will be addressed by a future story - either converting to production or lerna.

fix: gh-pages deployment process

---

src/_playground/App.js
src/_playground/App.scss
src/_playground/Routes.js
src/_playground/documentation/Description/Description.js
src/_playground/documentation/DocsTile/DocsTile.js
src/_playground/documentation/Header/Header.js

use 100% for viewport.
also begin to separate doc app styles from component override styles.
fixes #299

fix: set viewport to 100%; clean up docs styles a bit

---

src/_playground/App.scss
src/_playground/documentation/DocsTile/DocsTile.js

Adds light and dark mode for examples as seen in Fundamental NGX and Fiori Fundamentals.
fixes #300

chore: add background toggle for examples

---

src/DatePicker/DatePicker.test.js

Update unit tests for DatePicker component

fix: DatePicker update unit tests

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

While reviewing this component, noticed duplicate code as well as unnecessary code. This PR cleans up the code used for the DatePicker component.
fixes #342

fix: Refactor DatePicker component

---

.eslintignore
.gitignore
README.md
package-lock.json
package.json
scripts/build.js
scripts/start.js
src/_playground/App.js
src/_playground/App.scss
src/_playground/Routes.js
src/_playground/documentation/Home/Home.js
src/_playground/documentation/Markdown/MarkdownImporter.js

See https://github.com/SAP/fundamental-react/pull/318: too many merge conflicts, starting on fresh branch
fixes #298

chore: update docs pages with preamble, update nav

---

package.json

I was making improper use of the `bin` config option in `package.json`.  Since the script in this block isn't exported as part of the distribution package, adding this to the path causes a failure.
fixes #347

fix: Removed bin config option

---

src/Tabs/Tabs.test.js

Since the tab test holds some of its `<Tab>` children inside an array, all components in the array must have a unique key. 
I've updated the tests to include unique keys for this test only which fixes the issue. When using `<TabGroup>` to contain the `<Tab>` component this issue does not occur.

fix: Tab test throws React key warning

---

src/Calendar/Calendar.js
src/Calendar/Calendar.test.js

Updated component to set **currentDateDisplayed** on date click. Also sets the value to the first of a month after selection from the Month picker.  If the **currentDateDisplayed** does not get updated to the first of the month on Month change. There would be an issue when switching from March 30th to Feb.
fixes #334

fix: set currentDateDisplayed on date click

---

src/_playground/App.scss

When adding styles for pages imported from markdown, I inadvertently overrode styles for the Side Navigation component. 
fixes #354

fix: update css specificity for markdown

---

package.json

react-syntax-highlighter should be a devDep

chore: move syntax highlighter to dev Dep

---

src/_playground/App.scss

margin for block-level elements should always be applied to the bottom. cleaning up H1 here.
also cleaning up margin/padding for content area. gave no space on the right side

chore: H1 margin; normalize content padding

---

.npmrc
.travis.yml
ci-scripts/setup-npm.sh
package-lock.json
package.json

In the last PR to refine the release process, I moved the NPM credentials into a `.npmrc` file.  The problem is that those environment variables need to be present (even in a local development environment) in order to run any npm scripts.  This PR removes that file and restores a script file that will setup the `.npmrc` only during CI server deployments.

chore: Release process cleanup

---

src/Calendar/Calendar.js

Currently in the Calendar component when selecting a Month or Year the user has to click on the Month or Year to close the selector (see below)
This change will hide the Month/Year selector after making a selection

fix: hide Month/Year selector after selection

---

src/Calendar/Calendar.js
src/Calendar/Calendar.test.js

Set the currentYear value to the selected date object. 
fixes #357

fix: update currentYear on date selection

---

babel.config.js
devtools/remove-prop-descriptions/index.js

This is a very basic babel plugin to remove propDescriptions from the prod build. Babel uses AST Traversal, much like codemods. This _seems_ to do what we want it to do but I'd like to get @jbadan's eyes on this. 
fixes https://github.com/SAP/fundamental-react/issues/376

fix: basic babel plugin to remove propDescriptions

---

src/Icon/Icon.Component.js

Small fix that addresses how the icons were rendered in the example: https://sap.github.io/fundamental-react/icon

fix: icon-example-rendering

---

src/InputGroup/InputGroup.Component.js
src/InputGroup/InputGroup.js
src/_playground/documentation/Playground/Playground.js

Also sorts props in InputGroup
fixes #359

fix: playground labelText prop mix up

---

package-lock.json
package.json

We reference `prop-types` in our library but do not list it as a dependency. I _believe_ this works because `annotated-prop-types` lists `prop-types` as a dependency. We should list it as a dependency to avoid future bugs. Thanks @jbadan for pointing this out.

chore: add prop-types as a dependency

---

ci-scripts/publish.sh
package.json

The `gh-pages` package uses simple authentication by default which was causing the `fundamental-bot` user to fail authentication when attempting to publish the docs.  I added a `repo` argument that embeds the GitHub token so we can push to the `gh-pages` branch.
fixes #352

chore: Added repo arg to the gh-pages call

---

README.md
package-lock.json
package.json

`fiori-fundamentals` should be installed by the consumer, not us
leaving as a peer so we can at least require minimum versions of `fiori-fundamentals`

chore: change fiori fundamentals dependency status

---

devtools/buildIndexFiles.js

@chrismanciero found a bug that index file generation was failing on Travis when more than one component file existed in a directory. This fixes it.

fix: update index files generation to handle multiple component files in single directory

---

package.json
src/_playground/Routes.js

In the playground, hosting with Github pages doesn't support routing with SPAs very well because there is no server redirecting all requests to the index.html file.  
This is causing page refreshes or direct links to non-root routes (like https://sap.github.io/fundamental-react/datepicker) to return the Github 404 page.
This PR allows page refreshes and direct links by creating a 404.html file identical to the index.html file as part of the deploy script.  Github will direct 404s to this 404.html. 
It also provides a simple component for rendering a 404 within the docs

fix: Playground: Add a 404.html identical to index.html

---

src/Calendar/Calendar.js

The original issue (#358) describes the issue within `DatePicker` but it actually lies in the `Calendar` component calculation. The offset used for the calculation for the starting day of the month was causing issues with any month that started on Sunday. The offset could be increased to 7 (rather than 6) or removed completely (which is what I decided to do in this commit). The only difference would be that the previous week from previous month would be shown also.
For example, June 1st 2025 is a Sunday.
**Before fix** - June 1st 2025 is shown as a Saturday (incorrect) and Friday & Saturday are disabled rather than Saturday & Sunday.
**After Fix** - the day is corrected (June 1st 2025 is a Sunday) and Saturday & Sunday are disabled as expected.
fixes #358

fix: Remove offset for start of week date in Calendar

---

.travis.yml
package.json

Coveralls is currently causing all builds to fail in Travis. This is a known recurring issue on their end: 
https://github.com/lemurheavy/coveralls-public/issues/1264
This PR allows coveralls to fail without stopping the build.
related to #416

fix: temporarily disable coveralls

---

devtools/buildIndexFiles.js

The `buildIndexFiles.js` script only supported named exports in component files. This works fine when we have multiple components in one file as named exports. Since we want to implement the one component per file lint rule, we need to support default exports as well.

fix: CORUI-6264: Support default exports for components

---

src/_playground/App.scss
src/_playground/Routes.js

A few side navigation cleanup tasks:
* Reworked the side nav to use flex box (no more 90% height)
* Changed styling to match `fundamental-ngx` a bit more (with a React twist)
* Moved the search box into a non-scrollable area
* Fixed the list item transitions
* Set a fixed width for the side nav
* General CSS cleanup
fixes #422

fix: Reworked side navigation

---

README.md
package-lock.json
package.json

Bump fundamentals dependency to version with IE 11 css and reference IE 11 css distribution.
fixes https://github.com/SAP/fundamental-react/issues/436

chore: bump fundamentals version and reference ie 11 compat css

---

src/_playground/App.scss
src/_playground/documentation/DocsTile/DocsTile.js

docs: Add toggle right to left control to playground

---

src/Forms/FormInput.js
src/utils/constants.js

The state prop for FormInput has a list of valid values, but the prop now uses PropTypes.oneOf validator rather than .string
fixes #428

fix: forminput state proptype is now oneOf, not string

---

config/webpack.config.dev.js
config/webpack.config.prod.js

Add snap files to ignore glob in webpack prod config for github pages. This will prevent new files from being uploaded, but still need to be manually deleted from gh-pages branch.
New build folder output:
fixes #issueid

docs: ignoring snap files for ghpages build

---

src/ActionBar/_ActionBarActions.js
src/ActionBar/_ActionBarBack.js
src/ActionBar/_ActionBarHeader.js
src/Breadcrumb/_BreadcrumbItem.js
src/ListGroup/_ListGroupItem.js
src/ListGroup/_ListGroupItemActions.js
src/ListGroup/_ListGroupItemCheckbox.js
src/Menu/_MenuGroup.js
src/Menu/_MenuItem.js
src/Menu/_MenuList.js
src/Panel/_PanelActions.js
src/Panel/_PanelBody.js
src/Panel/_PanelFilters.js
src/Panel/_PanelFooter.js
src/Panel/_PanelHead.js
src/Panel/_PanelHeader.js
src/SideNavigation/_SideNavList.js
src/SideNavigation/_SideNavListItem.js
src/Tile/_ProductTileContent.js
src/Tile/_ProductTileMedia.js
src/Tile/_TileActions.js
src/Tile/_TileContent.js
src/Tile/_TileMedia.js
src/TreeView/TreeView.js
src/TreeView/_Tree.js
src/TreeView/_TreeBranch.js
src/TreeView/_TreeCol.js
src/TreeView/_TreeHead.js
src/TreeView/_TreeItem.js
src/TreeView/_TreeRow.js

As a follow-up to #452, I changed the display names of the sub components to be in the format that consumers will actually use these components (_e.g._ `ParentComponent.SubComponent`).  This will fix the issue with the code samples for each example.

docs: Updated display names for sub components

---

src/_playground/Routes.js

Add aria-label for Search input. GitHub logo has been updated since the issue was opened and no longer needs a label.
fixes #457

docs: Add aria-label for Search input

---

src/Forms/FormInput.js
src/Forms/Forms.Component.js
src/Forms/Forms.test.js
src/Forms/__snapshots__/Forms.test.js.snap
src/_playground/documentation/Properties/defaults.js
src/utils/constants.js

State prop description update was missed in https://github.com/SAP/fundamental-react/pull/453
These are now pulled from the Proptypes OneOf list.
Removed disabled, readOnly and help from state prop constant.
`readOnly` and `disabled` did not work as described (`state='disabled' or state='readonly'`) and instead are standalone attributes that work as expected when added like: `<FormInput disabled />` or `<FormInput readOnly />`. The examples have been updated as well as the prop list. 
`state='help'` also did not exist, although they have an example using a help input here: https://sap.github.io/fundamental/components/form.html#input-states, these are the same thing: https://sap.github.io/fundamental/components/form.html#input-help-elements, which we have also here: …

fix: update FormInput state prop description

---

src/Forms/FormInput.js

Call out more of FormInput's props explicitly for PropType validation using FormRadioItem as a model.
fixes #464

docs: Call out FormInput's props explicitly

---

src/_playground/App.scss

Background color with Toggle labels did not meet color contrast, this change bumps the contrast ratio to a passing 4.71:1. 
`#F3F4F5` was taken from the fundamental parent repo example containers.
fixes #461

docs: update example background color

---

package-lock.json
package.json
src/_playground/App.js
src/_playground/Routes.js
src/_playground/documentation/Home/Home.js
src/_playground/documentation/Template/ComponentPage.js
src/_playground/documentation/Template/MarkdownPage.js
src/_playground/documentation/index.js
src/_playground/documentation/utils/SetMeta.js

Using react-helmet-async, we can update the title and meta description in the head to be accurate on page change. I put the SetMeta component inside utils for now, but am open to moving it to it's own folder.
Also fixes the logo routing issue.
fixes #456 #468

docs: update title and meta information on page change

---

package-lock.json
package.json
src/ComboboxInput/ComboboxInput.test.js
src/ComboboxInput/__snapshots__/ComboboxInput.test.js.snap
src/Dropdown/__snapshots__/Dropdown.test.js.snap
src/LocalizationEditor/LocalizationEditor.test.js
src/LocalizationEditor/__snapshots__/LocalizationEditor.test.js.snap
src/Popover/Popover.js
src/Popover/Popover.test.js
src/Popover/__snapshots__/Popover.test.js.snap
src/Shellbar/Shellbar.test.js
src/Shellbar/__snapshots__/Shellbar.test.js.snap
src/Tile/__snapshots__/Tile.test.js.snap
src/TimePicker/TimePicker.test.js
src/TimePicker/__snapshots__/TimePicker.test.js.snap
src/_playground/_popper.scss
src/utils/_Popper.js

In preparation for the move of the popper.js CSS to the Fiori Fundamentals library, renamed the classes to retain "popover" as the block-level name and made "popper" an element.
_**NOTE:** A number of snapshot files changes because of the classname changes._

fix: Renamed popper CSS classes

---

src/Calendar/Calendar.test.js

Like #329, and #342 ,  Travis builds are failing due to our unit tests for dates not being hardcoded.
It will fail throughout tonight (Travis is on German time and therefore already it is already 3/29) and tomorrow because 2/29 does not exist.
fixes #issueid

fix: update failing calendar tests to work on all dates

---

src/ActionBar/ActionBar.test.js
src/ActionBar/_ActionBarHeader.js
src/ActionBar/__snapshots__/ActionBar.test.js.snap
src/Menu/Menu.test.js
src/Menu/_MenuGroup.js
src/Menu/__snapshots__/Menu.test.js.snap
src/Modal/Modal.js
src/Modal/Modal.test.js
src/Panel/Panel.test.js
src/Panel/_PanelHead.js
src/Panel/__snapshots__/Panel.test.js.snap
src/SideNavigation/SideNav.test.js
src/SideNavigation/_SideNavList.js
src/SideNavigation/__snapshots__/SideNav.test.js.snap
src/Tile/Tile.test.js
src/Tile/_ProductTileContent.js
src/Tile/_TileContent.js
src/Tile/__snapshots__/Tile.test.js.snap
src/_playground/documentation/Properties/defaults.js

`<h1>` headings were used in following components: 
* ActionBar 
* MegaMenu  (Deprecated - does not exist in FR)
* Menu 
* Modal 
* Panel 
* SideNavigation 
* Tile
* ProductTile
* Default header is now `<h3>` with the option to customize using `<h2>`-`<h6>`
* `<h1>` is not allowed due to a11y reasons (except in ActionBar)
*  updated unit tests for each component - I did not separate these into separate files as we have a story in the backlog to separate the testing files for each subcomponent
* update snapshots for each component 
* chose not to add additional examples as it didn't seem necessary with the props table explaining the options. Open for other opinions!
fixes #249 
Accompanied by changes in fundamental repo: https://github.com/SAP/fundamental/pull/1367
No visual changes in …

fix: make all heading elements customizable

---

src/Badge/Badge.Component.js
src/Badge/Counter.js
src/LocalizationEditor/LocalizationEditor.js
src/Menu/Menu.Component.js
src/Panel/Panel.Component.js
src/Table/Table.js
src/_playground/documentation/Properties/_PropertyDescription.js
src/_playground/documentation/Properties/_PropertyShape.js
src/_playground/documentation/Properties/_PropertyTable.js
src/_playground/documentation/Properties/_PropertyType.js
src/_playground/documentation/utils/getShapeTitle.js

Did some refactoring to make the `PropertyShape` component more generic so it will work with both `i18n` custom prop types _AND_ `shape` prop types.  Below are screenshots of both prop types.
Did some other minor cleanup:
- Changed some example titles/headings to prevent id collisions with the property tables
- Fixed an issue with `localizedText` for the `Counter` component
- Updated some prop descriptions where appropriate

docs: Property shapes

---

src/_playground/documentation/Example/Example.js

Opening the form modal in the docs would create a ref on the input.
Trying to turn the example code to a JSXString using react-element-to-jsx-string would cause an infinite loop trying to parse the ref.  This happens after the ref is created and has a current value because it is a circular thing to parse: ref -> current -> element -> ref -> current .....
This PR just ignores the ref prop when creating the JSX string.
fixes #462

docs: Fix form modal breaking docs site

---

ci-scripts/publish.sh
package-lock.json
package.json

It was found in the `fundamental` repo that the calls to GitHub API to build the release notes _could_ happen prior to the commits being pushed (or updated within GitHub).  To help ensure this works, I have moved the create release call below publish.
Also, updated to a new version of `github-assistant` that will include a "Documentation" section in the release notes.

chore: Release notes

---

src/SideNavigation/SideNav.js
src/SideNavigation/SideNav.test.js

Added onSelectItem callback to SideNav Component for a consumer to use prop when SelectedId is changed. 
Relates to issue #507 
fixes #508

fix: added onSelectItem callback to SideNav Component

---

src/Tabs/TabGroup.js
src/Tabs/TabGroup.test.js
src/Tabs/__snapshots__/TabGroup.test.js.snap

```js
React.Children.map(this.props.children, (child, index)
```
maintains null children in the map function while
```js
React.Children.toArray(this.props.children).map((child, index) => {
```
removes null values
fixes #514

fix: Use React.Children.toArray to prune null children in TabGroup 

---

src/Forms/FormRadioGroup.js
src/SideNavigation/SideNav.js
src/SideNavigation/_SideNavList.js
src/SideNavigation/_SideNavListItem.js
src/TreeView/TreeRow.test.js
src/TreeView/TreeView.js
src/TreeView/_BaseTree.js
src/TreeView/_TreeHead.js
src/TreeView/_TreeItem.js
src/TreeView/_TreeRow.js
src/TreeView/__snapshots__/TreeRow.test.js.snap

This prevents cloneElement throwing an error when a child is null, such as with
```jsx
{condition && <TreeView.Col ...}
```
- FormRadioGroup was safe because it had `React.isValidElement` checks, but I changed it to be consistent.
- Similar for SideNav
- TreeView had issues with the introduced test, which now passes
fixes #523

fix(Forms;SideNav;TreeView): Make React.Children null safe

---

src/Calendar/Calendar.test.js
src/Tabs/TabGroup.test.js

Currently have failing tests preventing us from submitting other PR's. 
Calendar:
* hardcoded date to omit issues with current date landing on the 31st. 
* test now looks similar to what we have for testing previous button
* added a new test and skipped it for now to be added once calendar component is refactored across fundamental. 
TabGroup: 
* Test was failing due to PR a month ago - fixed by gettingDOMNode from 'ul'

Fix: updated failing tests for tabgroup and calendar

---

ci-scripts/publish-rc.sh
ci-scripts/publish.sh
package.json

Standard versioning was off in the package-json file within lib because I copied it over before standard versioning was complete. It will now copy package-json file over once standard versioning is complete.
fixes #issueid

fix: updated publish scripts to copy package.json after standard versioning is complete

---

.eslintrc
package-lock.json
package.json

Reverting this change: https://github.com/SAP/fundamental-react/pull/625
This commit https://github.com/facebook/create-react-app/pull/6586/files breaks our start script by changing the way the arguments are passed to `createCompiler`
Also added eslint config to stop warning that cropped up from another bump.
fixes #issueid

fix: revert react-dev-utils breaking changes dep bump

---

README.md

The previous link required admin approval to join the slack workspace.
fixes #issueid

fix: update readme link for slack

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

Without doing a full rewrite at the moment, this is as close to a functional callback as we can get. Tests were a nightmare, so I decided to forgo them for this bandaid. 
This behaves slightly erratically as the input is not wired up to the calendar/sharing validation. 
Known bugs: Changes to the input don't necessarily update the date/trigger any event.
fixes https://github.com/SAP/fundamental-react/issues/498

fix: CORUI-6949: add onBlur callback to DatePicker

---

babel.config.js
package-lock.json
package.json

Do not use react-inline-elements transform as it is meant only for the final application.
fixes #512

fix: Do not use react-inline-elements transform 

---

src/Pagination/Pagination.js
src/Pagination/__snapshots__/Pagination.test.js.snap

`onClick` was being spread onto the container div and being called by each page.
fixes #747

fix: Pull onClick off of props in pagination before spreading

---

package.json

I believe this change might fix the bundlephobia errors we've been having. Because we `cd lib` then `npm publish`, there is no `lib/index.js`, just `index.js`.
I don't know how to test this besides merging and checking the build in bundlephobia 🤷‍♀
This might also fix the problem  @parostatkiem had in codepen.
fixes #issueid

chore: change main file path for bundlephobia

---

ci-scripts/publish-rc.sh
ci-scripts/publish.sh
package.json

In #776 , I moved build:copy-files to the build script. This actually needs to happen after standard-version runs on releases or else the package version number is the old one inside of lib for publishing.
fixes #issueid

fix: add build:copy-files after standard version has run

---

src/Popover/__stories__/Popover.stories.js
src/utils/_Popper.js

Cause: Mismatch between FD-style expected attribute name and FD-react property applied leading to appropriate styles not being applied to the popover.
Solution: Change popover `<div>`'s property names to match FD-style attribute selectors seen [here](https://github.com/SAP/fundamental-styles/blob/master/src/popover.scss#L210). 
* `data-placement` becomes `x-placement`
* `data-x-out-of-boundaries` becomes `x-out-of-boundaries`
* Storybook entry for popover placement [added](http://localhost:12123/?path=/story/components-popover--placement)
**Before** (chrome)
**After** (chrome)
fixes #740

fix: No Popover Arrow

---

src/Dropdown/Dropdown.test.js
src/Dropdown/__snapshots__/Dropdown.test.js.snap
src/Popover/Popover.js
src/Popover/Popover.test.js
src/Popover/__snapshots__/Popover.test.js.snap
src/Popover/__stories__/Popover.stories.js
src/Shellbar/Shellbar.js
src/Shellbar/__snapshots__/Shellbar.test.js.snap
src/Tile/Tile.test.js
src/Tile/TileActions.test.js
src/Tile/__snapshots__/Tile.test.js.snap
src/Tile/__snapshots__/TileActions.test.js.snap
src/utils/constants.js

Add following aria attributes to popover control/target.
* [aria-controls](https://www.w3.org/TR/wai-aria-1.1/#aria-controls)
* [aria-expanded](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded)
* [aria-haspopup](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup)
This allows screen readers and other assistive technologies to understand the popover interactions semantically.
fixes #791

fix: Add aria attributes to popover control

---

src/LayoutGrid/LayoutGrid.js
src/LayoutGrid/__snapshots__/LayoutGrid.test.js.snap
src/LayoutGrid/__stories__/LayoutGrid.stories.js

LayoutGrid class `fd-layout-grid--no-gap` had typo, `fd-layout-grid--nogap`
fixes #802

fix: layoutgrid no-gap typo fix

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

fix: provided a 'defaultValue' prop to the DatePicker

---

.eslintignore
src/Forms/Checkbox.test.js

We wanted to keep the unit tests that came out of this PR: https://github.com/SAP/fundamental-react/pull/849
Maybe we don't want to keep the TODO comment in the test, but I wanted to leave it in so reviewers could see the issue with using the component in an uncontrolled way.

chore: Add tests to Checkbox for indeterminate and defaultChecked

---

src/utils/_Popper.js
src/utils/modalManager.js
src/utils/modalManager.test.js

When a script tag containing fundamental react was included in the `<head>` of the document it was throwing an error.  
It looks like this was happening because the version of react-overlays that fundamental-react is using in the Popover depends on `document.body.appendChild` to calculate the scrollbar width from the ModalManager's constructor.
This change ensures that the calculation for `document.body.appendChild` will only happen when it is available.

fix: create modal manager, for Popover, on demand as a singleton

---

src/Pagination/Pagination.Component.js
src/Pagination/Pagination.js
src/Pagination/Pagination.test.js
src/Pagination/__snapshots__/Pagination.test.js.snap

feat#773: Added visiblePageTotal prop to Pagination component.
fixes #773

fix: 773: Added visiblePageTotal prop to Pagination component.

---

src/utils/_Popper.js

the 'onFocusOutside' handler of react-foco was removed. Using this trigger causes react-foco to handle the events in the capturing event phase which therefore then can't be handled by the component as the handler closes the Popover. As the Popover uses the onClickOutside function as a trigger to close the Popover content the onFocusOutside handler is not needed
As far as I can tell, the onFocusOutside handler is unnecessary. 
With mouse navigation, the Popver will close as soon as the use interacts with another component. 
With keyboard navigation, the popover can be closed with the Escape key(good luck Touchbar users 😂). This is the same behavior as before: When the Popover is opened with Space, subsequent Tab presses would cycle through options within the Popover.
fixes #877

fix: make popover usable within components having focus

---

src/DatePicker/DatePicker.js
src/Popover/Popover.js

Clicking the DatePicker will automatically focus the Calendar upon opening the Popover which isn't always desired if the user wants to directly edit the text field. Adds a prop to Popover disable the default opening of the Popover body when clicking the `control` element.

fix: disable trigger popover on click for datepicker

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js
src/utils/_Popper.js

Calls DatePicker onChange when a calendar item is selected. Before, it would never be called it all unless you typed in the field directly.
Adds spreadable `popoverProps`

fix: datepicker onchange on calendar selection, popover props

---

src/SearchInput/SearchInput.js
src/utils/_Popper.js

Fixes :
- Search error when popover is triggered. Cause by li element being created in SearchInput and passed to MenuList were it gets addonBefore prop appended. Used Menu.Item instead.
- Popover error when open and window scrolls down.
fixes #931

fix: search addonBefore error and popover out boundaries

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

Changes
* Validation ends up updating the Datepicker's state. Since state updates are asynchronous the `onBlur` should be called AFTER state updates as a callback. Otherwise, the consumer ends up with stale data.
* update `state.isoFormattedDate` after validation
* call `props.onChange` after validation, as auto-formatting may change `state.formattedDate`
Before
After

fix: datepicker onBur callback validation

---

src/Forms/Checkbox.js
src/Forms/FormRadioItem.js
src/InputGroup/InputGroup.js
src/MultiInput/MultiInput.js
src/Select/Select.js

```
actionClassNames
buttonContainerClassNames
labelClassNames
inputClassNames
listClassNames
tokenizerClassNames
vs
backdropClassName
contentClassName
inputClassName
popperClassName
tableBodyClassName
table....ClassName
referenceClassName
```
[BREAKING] The breaking change is the renaming of the `labelClasses` prop to `labelClassName` in `Checkbox.js`
These should either all be singular or all plural.  I chose singular to match the existing `className` prop
Note that this will be a breaking change for consumers.
fixes #911

feat: Standardize the plurality of className props and variables

---

src/DatePicker/DatePicker.js

Currently `this.props.onChange` is called from multiple places without checking if the `formattedDate` in the state has truly changed. This leads to `this.props.onChange` being called with the same payload multiple times. To prevent this we should explicitly check if formattedDate has changed before calling `this.props.onChange` with the new payload.

fix: call onChange only if formattedDate has changed

---

README.md

Getting fonts from `@sap-theming` has been confusing for consumers. We can now point to the downloadable font set. 
fixes #issueid

chore: update readme to point to font downloads

---

src/ComboboxInput/ComboboxInput.js
src/InputGroup/InputGroup.js
src/MultiInput/MultiInput.js
src/MultiInput/MultiInput.test.js
src/MultiInput/__stories__/__snapshots__/MultiInput.stories.storyshot
src/SearchInput/SearchInput.js
src/Select/Select.js

- adjust `widthSizingType` for popover-based components, mainly to account for the max 37.5rem width for list
- add missing `fd-list--dropdown` class to ComboboxInput
- `fd-input-group__input` class incorrectly applied to child div tokenizer in MultiInput, instead applied manually to `input`
- truncate MultiInput when more than 3 items are selected
- MultiInput still doesn't instantly update when setting a `widthSizingType`, which causes the width to be 'one step behind' when selecting/deselecting items.

feat: width adjustments for popover based components, class changes, MultiInput changes

---

README.md

Documentation fix. The sample has invalid comments.

fix: updated comment markers in css example

---

package.json

Because we now suggest adding fonts/icons from fiori-design-web, we no longer need to required @sap-theming as a peerDependency.
fixes #issueid

chore: no longer require @sap-theming as peer dep

---

.storybook/custom/components/DocsPage.js

This removes `disableStyles` from the documented props tables. Unfortunately, we can't just look for "internal use only" as it filters by prop name, not description. 
fixes #393

docs: do not document disableStyles in props table

---

src/Menu/_MenuItem.js
src/SearchInput/SearchInput.test.js

Fix for bug #1026
Changed the prop onclick on the MenuItem to onClick to keep it consistant. 
BREAKING CHANGE: MenuItem onclick prop renamed to onClick
fixes #issueid

Fix:#1026 Changed MenuItem onclick prop to onClick

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

Without these changes this test
```jsx
test('provide ISO-8601 format date with custom dateFormat in props', () => {
wrapper = mount(<DatePicker dateFormat='DD-MM-YYYY' defaultValue='01-06-2020' />);
expect(wrapper.state('isoFormattedDate')).toEqual('2020-06-01');
});
```
would fail with
```
Expected: "2020-06-01"
Received: "2020-01-06"
```
where the isoFormattedDate was created with switched month and day values
And this test
```jsx
test('should format isoFormattedDate when a custom dateFormat is passed in props', () => {
const blur = jest.fn();
const element = mount(<DatePicker
dateFormat='DD-MM-YYYY'
defaultValue='01-06-2020'
onBlur={blur} />).find('input[type="text"]');
element.find('input[type="text"]').simulate('click');
element.find('input[type="text"]').simulate('change', { target: …
```

fix: [DatePicker] Construct new moment objects with custom dateFormat

---

src/Popover/Popover.js
src/Shellbar/Shellbar.js
src/Shellbar/__stories__/Shellbar.stories.js
src/TreeView/__stories__/__snapshots__/TreeView.visual.storyshot

With this change
+ Shellbar passes popoverProps to SearchInput
+ SearchInput popoverProps default to `placement='bottom'` and `disableEdgeDetection=true`
+ Product Switch button gets aria-label from `productSwitch.label`
+ `productSwitch.label` prop is now required
+ `productSwitch.label` prop documented
+ Popover `widthSizingType ` prop documentation markdown is fixed. Earlier, using MD code 
fixes #1020

feat: 1020: Shellbar pass popoverProps to SearchInput

---

src/Calendar/Calendar.js
src/Calendar/Calendar.test.js

In this change, we use the complete minimal weekday abbreviations for all locales from moment.js in the Calendar component. There isn't a recommended length for weekday name abbreviations in the [Fiori design guidelines for datepicker](https://experience.sap.com/fiori-design-web/date-picker/).
Demo:
fixes #1103

fix: minimal weekday abbreviations

---

src/Shellbar/Shellbar.js
src/Shellbar/__stories__/Shellbar.stories.js

Product switch item in the Shellbar component does not have an option to show as preselected. Its available in fundamental-styles as below
https://sap.github.io/fundamental-styles/components/shellbar.html
fixes #issueid
#1107 
Added option to pre-select a product switch item in the Shellbar component.

feat:#1107 option to select productSwitchItem in Shellbar component

---

babel.config.js
package-lock.json
package.json

https://github.com/ValeryG/babel-plugin-client-only-require
fixes #issueid

fix: Use client-only-require for css imports

---

src/Forms/Checkbox.js
src/Forms/Checkbox.test.js
src/Forms/__stories__/Checkbox.stories.js
src/Forms/__stories__/__snapshots__/Checkbox.stories.storyshot
src/List/__stories__/__snapshots__/List.stories.storyshot
src/MultiInput/MultiInput.js
src/Table/__stories__/__snapshots__/Table.stories.storyshot

- `aria-checked` is unneeded on a native `input type="checkbox"` and was not properly reflecting the state of the checkbox
- `checked` and `defaultChecked` should be set independently
- MultiInput was changing Checkbox ids on every render
Out of Scope:
- clicking checkbox fast 3+ times results in a crash in Chrome only (see https://github.com/SAP/fundamental-styles/issues/1197)

fix: checkbox a11y

---

src/Calendar/Calendar.js
src/InputGroup/InputGroup.js
src/utils/_Popper.js

```
Warning: Failed prop type: The prop `innerRef` is marked as required in `Popper`, but its value is `undefined`.
in Popper (created by FormValidationOverlay)
in FormValidationOverlay (created by InputGroup)
```
```
Warning: React does not recognize the `validationState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `validationstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in span (created by InputGroup.Addon)
in InputGroup.Addon (created by DatePicker)
```
```
Warning: Received `false` for a non-boolean attribute `x-out-of-boundaries`.
If you want to write it to the DOM, pass a string instead: x-out-of-boundaries="false" or …
```

fix: Clear up DOM warnings

---

.storybook/custom/components/Import.js
README.md
ci-scripts/publish-rc.sh
ci-scripts/publish.sh
package.json
src/Button/__stories__/Button.stories.js
src/Button/__stories__/ButtonSegmented.stories.js
src/Button/__stories__/__snapshots__/Button.stories.storyshot
src/Button/__stories__/__snapshots__/ButtonSegmented.stories.storyshot
src/Tabs/__stories__/TabGroup.stories.js
src/Tabs/__stories__/__snapshots__/TabGroup.stories.storyshot

This helps consumers `npm link` the repo locally.
BREAKING CHANGE: All imports from subdirectories will need to include the `lib` in their path now.

feat: Publish the package with a lib directory

---

src/Select/Select.js
src/Select/__stories__/__snapshots__/Select.stories.storyshot

- disable Popover triggers on disabled and readonly Select
- move onClick to right component

fix: prevent disabled and readonly select from opening

---

src/Popover/Popover.js
src/Popover/Popover.test.js
src/Popover/__stories__/Popover.stories.js
src/utils/_Popper.js

This came up as an improved way to implement fallback placements for popper components.  Basically the popperPlacement prop can be a single string and utilize Popper's default of flipping to the opposite placement
i.e. "bottom-end" would flip to "top-end" by default
or they can specify an array of placements to use.  `popperPlacement={['bottom-end', 'right', 'top']}`
This needed to be implemented to better support flip containers, DOM elements which the popper should stay within, in this PR https://github.com/SAP/fundamental-react/pull/1122. 
NOTE: The exposed `fallbackPlacements` prop has only been in an rc release, so it's not a breaking change outside of the current rc
fixes #issueid

feat: Use the popperPlacement prop to allow fallbackPlacements

---

package-lock.json
package.json
src/DatePicker/DatePicker.js
src/utils/CustomPropTypes/CustomPropTypes.js

fix: DatePicker cleanup PropTypes

---

devtools/buildIndexFiles.js
devtools/buildVisualStories.js
src/Popover/Popover.js
src/utils/CustomPropTypes/CustomPropTypes.js
src/utils/_Popper.js

A consumer of this library was running into the same issues as buildIndex was having where global.Element was not defined in a step of their build process.
If we can get away with it, a prop-type check shouldn't require a special override of the global namespace for Node environments.

fix: Do not throw an error if processing the code without the browser api

---

src/StepInput/StepInput.js
src/StepInput/__stories__/StepInput.stories.js
src/StepInput/__stories__/__snapshots__/StepInput.stories.storyshot

Issue #1129
when stepInput is rendered as readonly, (+) button is shown. No buttons should be shown in readonly mode. 
https://sap.github.io/fundamental-styles/?path=/docs/components-stepinput--primary#read-only
fixes #issueid

Fix: #1129 Fixing error in showing + button for readOnly StepInput

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js

The className prop for the DatePicker shouldn't be applied to the nested InputGroup in addition to the outer div.  I could see having a different prop `inputClassName` (or something) for this.
I see the convention as adding the className prop to the outermost wrapper.
fixes #1135

fix: Only add the className prop to DatePicker children once

---

src/DatePicker/DatePicker.js
src/Popover/Popover.js
src/utils/_Popper.js

If a DatePicker component is included in a modal, pressing escape will close both the DatePicker and modal as they have different modal managers. This PR allows for a custom modal manager to be passed down from a parent component.

fix: allow custom modal manager for DatePicker

---

.storybook/preview.js
.storybook/static/unnormalize.css

In this change, we define styles for an unnormalized theme. This will allow us to validate if components have self-contained styles.
For example, unnormalized `Button`:

chore: add an unnormalized theme

---

package.json

`-m` or `--message` is deprecated https://github.com/conventional-changelog/standard-version/blob/master/command.js#L33
Instead of using `%s` we can use `{{currentTag}}` -- https://github.com/conventional-changelog/standard-version/blob/ae032bfa9268a0a14351b0d78b6deedee7891e3a/test.js#L1244

chore: change standard-version commit message format

---

src/Calendar/Calendar.js

- Remove `'assertive'` `aria-live` region on header, and instead use polite region for all announcements. This ensures the initially-focused date is read out and the previous/next buttons aren't unexpectedly read when opening the calendar.
- Provide separate instructions for year view and month view. This helps add context when switching to month and year view, and helps work around the fact that the aria-live announcement will not read out if the same instructions are simply re-populated.
- Provide instructions after selecting a first date for range selection.
- JAWS and VoiceOver: ensure announcements described above are properly done
- VoiceOver + Chrome has a known issue where it will read polite announcements twice

fix: improve screen reader instructions for DatePicker

---

src/SearchInput/SearchInput.js
src/SearchInput/SearchInput.test.js
src/SideNavigation/SideNav.js
src/SideNavigation/SideNav.test.js

If the callback with an event is included in the callback of setState the event is not persisted and we lose the event.target
You will see warnings like this:
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
in SideNav (created by storyFn)
in provider (created by Provider)
in div (created by Provider)
in Provider (created by storyFn)
in storyFn
in ErrorBoundary
```
> “Warning: This synthetic event is reused for performance reasons”
This warning is triggered when we try to access to a React synthetic event in an …

fix: Move SearchInput and SideNav callbacks outside of setState.

---

src/utils/_Popper.js
src/utils/_PopperContainer.js

The original way of creating a Portal in Popper would fail in server-side rendering due to the reference to `document`.

fix: refactor popper portal

---

src/Forms/Checkbox.js
src/Forms/Checkbox.test.js
src/Forms/FormRadioItem.js
src/Forms/__stories__/Checkbox.stories.js

In this change, we update the Checkbox component to apply `className` value to the wrapping `FormItem` component instead of the internal `input`. This is to be consistent with the behavior in other Form components.
Is this a breaking change?

fix: Checkbox classname

---

src/Forms/Checkbox.js
src/Forms/Checkbox.test.js
src/Forms/_FormValidationOverlay.js

This is a necessary change for correct class names to be passed to the popper wrapping element and styles be correctly applied. This is linked to PR: https://github.concur.com/coreui/nui-widgets-lab/pull/124
Edit: replaced `validationOverlayProps` with `validationClassName` thereby leveraging the existing `className` prop within `FormValidationOverlay`.
Additionally, corrected a small syntax error for `PropTypes` inside of `FormValidationOverlay`.
Features:
- added new prop: `validationOverlayProps`

feat: validation class prop

---

src/Select/Select.js
src/Select/Select.test.js
src/Select/__stories__/Select.stories.js
src/Select/__stories__/__snapshots__/Select.stories.storyshot

`onBlur` is now only triggered when leaving the component - via `onClickOutside` or by leaving the select field **AND** the dropdown list. Previously, `onBlur` was being fired when leaving the select field and navigating inside of the dropdown list items.
fixes #1159

fix: select onfocus onblur callbacks called at appropriate times

---

src/ActionBar/ActionBar.test.js
src/ComboboxInput/ComboboxInput.test.js
src/List/ListHeader.test.js
src/Menu/_MenuItem.js
src/ObjectStatus/ObjectStatus.test.js
src/Pagination/Pagination.js
src/Tile/Tile.test.js
src/Time/Time.js
src/Time/__stories__/__snapshots__/Time.stories.storyshot
src/TimePicker/TimePicker.js
src/Token/Token.test.js

Cleans up test warnings from a couple components (definitely not all of them!)
Breaking change: removed unused `spinners` prop from `TimePicker` and `Time` components
fixes #issueid

chore: cleanup some test warnings

---

src/Switch/Switch.js
src/Switch/Switch.test.js

Deriving Switch's checked state from the `checked` prop, which fixes the refresh of checked state on update of the component.
fixes #977

fix: fundamental Switch state doesn't refresh 

---

src/ComboboxInput/ComboboxInput.js
src/ComboboxInput/ComboboxInput.test.js
src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js
src/Forms/Checkbox.js
src/Forms/Checkbox.test.js
src/Forms/FormInput.js
src/Forms/FormInput.test.js
src/Forms/FormTextArea.test.js
src/Forms/FormTextarea.js
src/Forms/_FormValidationOverlay.js
src/Forms/_FormValidationOverlay.test.js
src/InputGroup/InputGroup.js
src/InputGroup/InputGroup.test.js
src/MultiInput/MultiInput.js
src/MultiInput/MultiInput.test.js
src/SearchInput/SearchInput.js
src/SearchInput/SearchInput.test.js
src/Select/Select.js
src/Select/Select.test.js
src/StepInput/StepInput.js
src/StepInput/StepInput.test.js

I want to be able to add a custom class to the Popper in FormMessage from any component consuming it.
Additionally added documentation + tests for `validationOverlayProps.wrapperProps`
Added tests
Continuation of https://github.com/SAP/fundamental-react/pull/1185
fixes #issueid

feat: add additional props for customization to validationOverlayProps

---

src/utils/CustomPropTypes/CustomPropTypes.js

Consumers are seeing this warning if running code containing the DatePicker for SSR
```
Warning: Failed prop type: Popper: prop type `flipContainer` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.
in Popper
in Popover
in div
in DatePicker
```
fixes #issueid

fix: in SSR `null` is not a valid prop-type

---

src/ComboboxInput/ComboboxInput.js
src/ComboboxInput/ComboboxInput.test.js
src/ComboboxInput/__stories__/ComboboxInput.stories.js
src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js
src/Forms/_FormMessage.js
src/MultiInput/MultiInput.js
src/MultiInput/MultiInput.test.js
src/Select/Select.js

In this change we
* Update ComboboxInput, DatePicker, and MultiInput to not show input aligned semantic messages when the popover is open. This is because the popover is expected to show this message. Hence we do not want to duplicate the semantic message.
* Use appropriate styles for validation messages that are inside popovers

fix: multiple validationState messages + popover validation message styles

---

package-lock.json

Dependabot isn't addressing the security warning weirdly... this is the output of npm audit fix.

chore: npm audit for security updates

---

.github/CONTRIBUTING.md
.reuse/dep5
LICENSE.txt
LICENSES/Apache-2.0.txt
NOTICE.txt
README.md

Migrate Fundamental React from CLA to DCO
The SAP Open Source Program Office is working on adopting external standards and best practices wherever possible and making contributions to our open source projects as easy as possible. Therefore, some adjustments are required in this repository:
* Switch from Contributor License Agreement (CLA) to Developer Certificate of Origin (DCO)
* Generate license and copyright information with the 'Reuse' tool of the Free Software Foundation Europe (FSFE)
* Adjust the license file to use standard text for [Apache License, Version 2.0
](https://opensource.org/licenses/Apache-2.0)
fixes #1158

chore: switching from CLA to DCO

---

src/DatePicker/DatePicker.js

DatePicker component needs list styles because it uses the `fd-list--has-message` class.

fix: datepicker add list styles

---

src/Shellbar/Shellbar.js
src/Shellbar/__stories__/Shellbar.stories.js

In this change, we update the Shellbar component to accept props to be spread to the Popovers of the action menu, collapsed mobile menu, notifications menu, product menu, product switch popover, and the profile menu. This will allow consumers to customize these; for example, set the `placement`.
fixes #919

feat: make shellbar popovers customizable

---

src/DatePicker/DatePicker.js

Change Datepicker footerButtonProps type from string to object.

fix: Datepicker footerButtonProps type

---

src/utils/focusManager/focusManager.js

In this change, we fix an issue with the focus manager which prevented focus from traveling into a tabbable element positioned after a focus-manged grid inside a popover. Using a grid, with controls in its cells, inside a popover (DatePicker) caused tabbable nodes expected by the focus manager to be changed by the grid manager. This is seen in Datepicker where it was not possible to navigate to the today footer button with keyboard tabbing.

fix: focus manager use with grid manager

---

src/index.js

Add the missing `Title`-Component to the `index.js`

fix: add title to index.js

---

src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js
src/DatePicker/__stories__/DatePicker.stories.js
src/DatePicker/__stories__/__snapshots__/DatePicker.stories.storyshot

A readOnly DatePicker field should not have a button
Breaking Change: A readOnly DatePicker field does not have an InputGroup Button
IE11

feat: Hide the DatePicker button when readOnly is true

---

.storybook/custom/custom.scss
README.md

css from fundamental-styles uses rems. 1rem equals the font size of the html element. While most browsers have 16px as the base, we might want to explicitly call it out. I'm not sure if this pr is necessary 🤷‍♂️ 
fixes #1236

docs: add base font size to html in readme instructions

---

devtools/buildVisualStories.js
package-lock.json
package.json
src/Calendar/Calendar.js
src/DatePicker/DatePicker.js
src/DatePicker/DatePicker.test.js
src/DatePicker/__stories__/DatePicker.stories.js

BREAKING CHANGE:
* Remove `todayAction` property from Datepicker
* Add `todayActionType` property to Datepicker to configure the type of today action.
* Update Datepicker to use a label for the Today action button from `localizedText.todayLabel`.
chore:
clean old visual stories before building new ones.
```jsx
<DatePicker
todayAction={{
type: 'select',
label: 'Today'
}}
/>
```
```jsx
<DatePicker
localizedText={{
todayLabel: 'Today'
}}
todayActionType= 'select'
/>
```

fix: Datepicker today actions props interface

---

src/Select/Select.js
src/Select/Select.test.js

Fixes an issue where the select component did not set the `selectedKey` when new options were set.
This change should cause select to set the `selectedKey` when it or `options` prop change

fix: Select selectedKey behavior

---

src/DatePicker/__stories__/__snapshots__/DatePicker.stories.storyshot
src/TimePicker/TimePicker.js
src/TimePicker/TimePicker.test.js

(https://github.com/SAP/fundamental-react/issues/1390)
fixes #1390

fix: added fix to support the behavior of twelve hour timepicker format if seconds not passed"

---

.gitignore
src/Dialog/Dialog.js

Restore scroll position after a dialog closes
Fixes #1395

fix: restore scroll position after dialog closes

---

.gitignore
package-lock.json
package.json

This PR update `react-popper` dependency to latest version, so that popover component can have correct alignment under `React 18` strictMode.
I have tested it in my own React 18 project, all the component seem to work fine, but I'm not confident about that.
I was trying to update the test to support React 18, but a lot of code need to be refactored and updated, and I cannot do that in hours, sorry for that. Currently, the project was still tested with React 17, but have set the peerDependency support React 18. I'm not quite sure if it is OK. (This PR does not contain any source code changes)
fixes #1434

feat: update react-popper to support react18

---

.storybook/custom/components/DocsPage.js
src/Shellbar/Shellbar.js
src/Shellbar/__stories__/Shellbar.stories.js
src/SideNavigation/_SideNavListItem.js

feat: add compact option to product menu, remove console errors

---

src/Shellbar/Shellbar.js
src/Shellbar/__stories__/__snapshots__/Shellbar.stories.storyshot
src/SideNavigation/_SideNavListItem.js
src/SideNavigation/__stories__/SideNav.stories.js
src/SideNavigation/__stories__/__snapshots__/SideNav.stories.storyshot

- revert compact option from product switch - the same thing can be done using actions when we'll add some features there
- add label and onclick to actions
- add a possibility to use nodes instead of just strings to sidensv

feat: add an option to fire onclick event on actions menu, revert compact option for product switch
